---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

inputs:
- name: rotate-password-tasks
- name: env # contains the env file with target OpsMan Information

params:
  ENV_FILE: env.yml

run:
  path: rotate-password-tasks/tasks/flag-recreate-all-vms/task.sh
